apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-config
spec:
  interval: 1h
  path: ./manifests/monitoring/monitoring-config
  targetNamespace: observability
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-monitoring
  healthChecks:
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: podmonitors.monitoring.coreos.com
