apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: aws-efs-csi-driver
spec:
  interval: 1h
  path: ./deploy/kubernetes/overlays/stable/
  targetNamespace: kube-system
  prune: true
  sourceRef:
    kind: GitRepository
    name: aws-efs-csi-driver
