apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
metadata:
  name: aws-efs-csi-driver-kustomization
resources:
  - aws-efs-csi-driver-sources.yaml
  - aws-efs-csi-driver.yaml
