apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  labels:
    kustomize.toolkit.fluxcd.io/name: system
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: aws-efs-csi-driver
  namespace: kube-system
spec:
  patches:
    # https://github.com/kubernetes-sigs/aws-efs-csi-driver/issues/962
    - patch: |
        - op: remove
          path: /spec/template/spec/hostNetwork
      target:
        kind: DaemonSet
        name: efs-csi-node
        namespace: kube-system
    - patch: |
        - op: add
          path: /metadata/annotations/eks.amazonaws.com~1role-arn
          value: arn:aws:iam::537928299818:role/simple-cluster-efs-csi
      target:
        kind: ServiceAccount
        name: efs-csi-(controller|node)-sa
        namespace: kube-system
