---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki-stack
  namespace: observability
spec:
  chart:
    spec:
      version: "~>2.9"
  values:
    loki:
      enabled: true
      isDefault: false # To avoid clashing with Prometheus, the default data source
      serviceMonitor:
        enabled: true
        interval: 30s
        additionalLabels:
          tier: cluster
      persistence:
        enabled: true
      serviceAccount:
        annotations:
          "eks.amazonaws.com/role-arn": "arn:aws:iam::537928299818:role/simple-cluster-loki-storage"
      storage:
        type: "s3"
        s3:
          region: eu-north-1
        bucketNames:
          chunks: loki-storage-simple-cluster-x7g9k3
          ruler: loki-storage-simple-cluster-x7g9k3
          admin: loki-storage-simple-cluster-x7g9k3
    promtail:
      enabled: true
      serviceMonitor:
        enabled: true
        interval: 30s
        additionalLabels:
          tier: cluster
    fluent-bit:
      enabled: false
    grafana:
      enabled: false
    prometheus:
      enabled: false
