---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki-stack
  namespace: observability
spec:
  chart:
    spec:
      version: "~>2.9"
  values:
    loki:
      enabled: true
      isDefault: false # To avoid clashing with Prometheus, the default data source
      image:
        tag: 2.8.2 # Overwrites 2.6.1
      serviceMonitor:
        enabled: true
        interval: 30s
        additionalLabels:
          tier: cluster
      persistence:
        enabled: true
      serviceAccount:
        annotations:
          "eks.amazonaws.com/role-arn": "arn:aws:iam::537928299818:role/simple-cluster-loki-storage"
      config:
        schema_config:
          configs:
          - from: "2023-01-01" # Arbitrary date in the past
            store: tsdb
            object_store: s3
            schema: v12
            index:
              prefix: index_
              period: 24h
        storage_config:
          tsdb_shipper:
            shared_store: s3
            cache_ttl: 24h
          aws:
            region: eu-north-1
            bucketnames: loki-storage-simple-cluster-x7g9k3
            s3forcepathstyle: false
        compactor:
          shared_store: s3
          compaction_interval: 5m
    promtail:
      enabled: true
      serviceMonitor:
        enabled: true
        interval: 30s
        additionalLabels:
          tier: cluster
    fluent-bit:
      enabled: false
    grafana:
      enabled: false
    prometheus:
      enabled: false
