---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
resources:
  - namespace.yaml
  - ../base/grafana-loki
  - ../base/kube-prometheus-stack
  - ../base/flux-monitoring
patchesStrategicMerge:
  - grafana-loki-values.yaml
  - kube-prometheus-stack-values.yaml
