---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
metadata:
  name: prometheus-kustomization
resources:
  - kube-prometheus-stack-sources.yaml
  - kube-prometheus-stack.yaml
