name: Terraform Checks

on:
  pull_request:
    paths:
    - 'terraform/**'

env:
  TERRAFORM_SRC: terraform
  TFLINT_CFG: .tflint.hcl

jobs:
  terraform-fmt:
    name: Check Terrform code formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Run terraform fmt
        uses: dflook/terraform-fmt-check@v1
        with:
          path: ${{ env.TERRAFORM_SRC }}
  tflint:
    name: Run TFLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Cache plugin dir
        uses: actions/cache@v3
        with:
          path: ~/.tflint.d/plugins
          key: ${{ runner.os }}-tflint-${{ env.TFLINT_CFG }}
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v3
        with:
          tflint_version: latest
      - name: Show TFLint version
        run: tflint --version
      - name: Init TFLint
        run: tflint --init
        env:
          # https://github.com/terraform-linters/tflint/blob/master/docs/user-guide/plugins.md#avoiding-rate-limiting
          GITHUB_TOKEN: ${{ github.token }}
      - name: Run TFLint
        run: tflint --config="../${{ env.TFLINT_CFG }}" --chdir="${{ env.TERRAFORM_SRC }}" --format compact
